FROM quay.io/fedora/fedora-bootc:43-x86_64 AS builder

RUN /usr/libexec/bootc-base-imagectl build-rootfs --manifest=minimal /target-rootfs

FROM scratch

COPY --from=builder /target-rootfs/ /

RUN <<EORUN
set -xeuo pipefail
dnf -y install vim
dnf clean all
rm /var/{log,cache,lib}/* -rf
bootc container lint
EORUN

LABEL containers.bootc 1
LABEL ostree.bootable 1

ENV container=oci

STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]